version: "3.9"

networks:
  bank-network:
    driver: bridge

services:
  bank-postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_db
    ports:
      - "5432:5432"
    volumes:
    #  - /home/diego/Documents/postgres-data:/var/lib/postgresql/data
    - ./create_bank_db_test.sh:/docker-entrypoint-initdb.d/create_bank_db_test.sh
    networks:
      - bank-network    

  bank-api:
    build: ./
    environment:
      DB_HOST: bank-postgres
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - bank-postgres